import {id,oneOf,roles,publicUser,fail} from './core.js';
export function installAdmin(c){const {route,store,stamp,options}=c;const s=()=>store.state;const retention=Number(options.backupRetention??process.env.BACKUP_RETENTION??7);if(!Number.isInteger(retention)||retention<1||retention>90)throw new Error('BACKUP_RETENTION must be 1–90');
 async function backup(user=null){const b={id:id(),createdAt:stamp()};const snapshot=structuredClone(s());snapshot.sessions=[];snapshot.tokens=[];snapshot.mail=[];await store.db.transaction(async tx=>{await tx.query('INSERT INTO backups (id,created_at,body) VALUES ($1,$2,$3)',[b.id,b.createdAt,JSON.stringify(snapshot)]);await tx.query('DELETE FROM backups WHERE id NOT IN (SELECT id FROM backups ORDER BY created_at DESC,id DESC LIMIT $1)',[retention]);});c.audit(user,'backup.created',b.id);return b;}
 c.runBackupSchedule=()=>store.exclusive(async()=>{const d=new Date(c.now());const day=d.toISOString().slice(0,10);if(!s().settings.backupEnabled||d.getUTCHours()<s().settings.backupHour||s().lastBackupDay===day)return false;await backup();s().lastBackupDay=day;await store.save();return true;});
 route('get','/admin','admin',async req=>({users:s().users.map(publicUser),problems:s().problems.map(p=>c.problemView(p,req.user)),flags:s().flags,audit:s().audit.slice().reverse(),backups:(await store.db.query('SELECT id,created_at AS "createdAt" FROM backups ORDER BY created_at DESC')).rows,settings:s().settings}));
 route('patch','/admin/users/:id','admin',req=>{const u=s().users.find(u=>u.id===req.params.id);if(!u)fail(404,'User not found');const role=req.body.role===undefined?u.role:oneOf(req.body.role,roles,'role');const active=req.body.active===undefined?u.active:req.body.active;if(typeof active!=='boolean')fail(400,'active must be boolean');if(u.id===req.user.id&&(!active||role!=='admin'))fail(409,'Cannot deactivate or demote yourself');if(u.role==='admin'&&u.active&&(!active||role!=='admin')&&s().users.filter(x=>x.active&&x.role==='admin').length<=1)fail(409,'Cannot remove the last active administrator');u.role=role;u.active=active;s().sessions=s().sessions.filter(x=>x.userId!==u.id);c.audit(req.user,'user.updated',u.id);return publicUser(u);});
 route('post','/admin/flags/:id/resolve','admin',req=>{const f=s().flags.find(f=>f.id===req.params.id);if(!f)fail(404,'Flag not found');f.resolved=true;f.resolvedAt=stamp();f.resolvedBy=req.user.id;c.audit(req.user,'flag.resolved',f.id);return {ok:true};});
 route('patch','/admin/settings','admin',req=>{if(typeof req.body.backupEnabled!=='boolean'||!Number.isInteger(req.body.backupHour)||req.body.backupHour<0||req.body.backupHour>23)fail(400,'Provide backupEnabled boolean and backupHour 0–23 (UTC)');s().settings={backupEnabled:req.body.backupEnabled,backupHour:req.body.backupHour};c.audit(req.user,'settings.updated','backup');return s().settings;});
 route('post','/admin/backups','admin',req=>backup(req.user));
 route('post','/admin/backups/:id/restore','admin',async req=>{if(req.body.confirmation!=='RESTORE')fail(400,'Type RESTORE to confirm');const result=await store.db.query('SELECT body FROM backups WHERE id=$1',[req.params.id]);if(!result.rows.length)fail(404,'Backup not found');const restored=result.rows[0].body;if(!restored.users?.some(u=>u.active&&u.role==='admin')||!Array.isArray(restored.problems)||!Array.isArray(restored.projects))fail(409,'Backup failed validation');const audit=s().audit;restored.audit=audit;restored.sessions=[];restored.tokens=[];restored.mail=[];store.state=restored;c.audit(req.user,'backup.restored',req.params.id);await store.db.transaction(async tx=>{await tx.query('UPDATE application_state SET body=$1 WHERE id=1',[JSON.stringify(restored)]);});return {ok:true};});
 let timer;if(options.scheduler!==false){timer=setInterval(()=>c.runBackupSchedule().catch(()=>{console.error('Scheduled backup failed; administrator intervention required.');}),60000);timer.unref();}c.stopSchedule=()=>clearInterval(timer);
}
