import nodemailer from 'nodemailer';
import {id,token,hash,email,text,oneOf,roles,passwordHash,passwordMatches,publicUser,fail} from './core.js';
export function installAuth(c){const {route,store,now,stamp,demoMode,options}=c;const smtp=options.smtp??(process.env.SMTP_HOST?{host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT??587),secure:process.env.SMTP_SECURE==='true',auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}:undefined}:null);const transport=smtp?nodemailer.createTransport({...smtp,requireTLS:!smtp.secure,connectionTimeout:10000,greetingTimeout:10000,socketTimeout:15000,disableFileAccess:true,disableUrlAccess:true}):null;c.emailMode=transport?'SMTP configured':demoMode?'demo preview (not delivered)':'unconfigured';
 c.sendMail=async(to,subject,body)=>{if(demoMode&&to.endsWith('@afrisolve.demo')){store.state.mail.push({id:id(),to,subject,text:body,createdAt:stamp()});return 'demo preview (not delivered)';}if(!transport)fail(503,'Email is not configured. Ask an administrator to configure SMTP.');try{const sent=await transport.sendMail({from:process.env.SMTP_FROM??'AfriSolve <noreply@afrisolve.example>',to,subject,text:body});if(!sent.accepted?.length)throw new Error('Not accepted');return 'SMTP accepted (delivery not guaranteed)';}catch{fail(503,'Email service unavailable. Please try again later.');}};
 async function issue(u,type){const raw=token();store.state.tokens=store.state.tokens.filter(x=>x.userId!==u.id||x.type!==type);store.state.tokens.push({key:hash(raw),userId:u.id,type,expiresAt:now()+(type==='verify'?86400000:3600000)});const base=process.env.APP_ORIGIN??'http://127.0.0.1:5173';return c.sendMail(u.email,type==='verify'?'Verify your AfriSolve email':'Reset your AfriSolve password',`${type==='verify'?'Verify your email':'Reset your password'}: ${base}/?action=${type}&token=${raw}\nThis link expires and works once. If you did not request it, ignore this email.`);}
 route('get','/demo/mail',false,req=>{if(!demoMode)fail(404,'Not found');const to=email(req.query.email);if(!to.endsWith('@afrisolve.demo'))fail(403,'Only fictional demo mail is available');return store.state.mail.filter(m=>m.to===to).slice().reverse();});
 route('post','/auth/register',false,async req=>{const role=oneOf(req.body.role,roles.filter(x=>x!=='admin'),'role');const e=email(req.body.email);if(store.state.users.some(u=>u.email===e))fail(409,'This email is already registered');const u={id:id(),name:text(req.body.name,'Name',100,2),email:e,role,country:text(req.body.country,'Country',100),institution:text(req.body.institution??'','Institution',200,0),bio:'',expertise:'',avatar:'',verified:false,active:true,demo:false,passwordHash:await passwordHash(req.body.password),createdAt:stamp()};store.state.users.push(u);const delivery=await issue(u,'verify');c.audit(u,'account.register',u.id);return {message:`Account created. Check your email to verify: ${delivery}.`,email:e};});
 route('post','/auth/login',false,async(req,res)=>{const u=store.state.users.find(u=>u.email===email(req.body.email));if(!u||!await passwordMatches(req.body.password,u.passwordHash))fail(401,'Invalid email or password');if(!u.active)fail(403,'Account deactivated');if(!u.verified)fail(403,'Verify your email before signing in');if(req.body.remember!==undefined&&typeof req.body.remember!=='boolean')fail(400,'remember must be boolean');c.session(req,res,u,req.body.remember===true);c.audit(u,'account.login',u.id);return {user:publicUser(u)};});
 function redeem(raw,type){const key=hash(text(raw,'Token',128));const record=store.state.tokens.find(x=>x.key===key&&x.type===type&&x.expiresAt>now());if(!record)fail(400,'Invalid or expired token');store.state.tokens=store.state.tokens.filter(x=>x!==record);return store.state.users.find(u=>u.id===record.userId);}
 route('post','/auth/verify',false,req=>{const u=redeem(req.body.token,'verify');u.verified=true;return {message:'Email verified. You can now sign in.'};});
 route('post','/auth/forgot',false,async req=>{const e=email(req.body.email);if(!transport&&!(demoMode&&e.endsWith('@afrisolve.demo')))fail(503,'Email is not configured');const u=store.state.users.find(u=>u.email===e&&u.active);if(u&&!u.demo)await issue(u,'reset');return {message:'If an eligible account exists, a reset link has been sent or is in the fictional demo mail preview.'};});
 route('post','/auth/reset',false,async req=>{const p=await passwordHash(req.body.password);const u=redeem(req.body.token,'reset');u.passwordHash=p;store.state.sessions=store.state.sessions.filter(s=>s.userId!==u.id);c.audit(u,'account.password-reset',u.id);return {message:'Password reset. Sign in with your new password.'};});
}
