import {id,text,oneOf,fail,publicUser} from './core.js';
export function installMentors(c){const {route,store,stamp}=c;const s=()=>store.state;
 route('get','/mentors',true,req=>{const q=String(req.query.q??'').toLowerCase();return s().users.filter(u=>u.role==='mentor'&&u.verified&&u.active&&`${u.name} ${u.expertise} ${u.bio}`.toLowerCase().includes(q)).map(publicUser);});
 route('post','/mentors/register',true,req=>{if(req.user.role==='admin')fail(403,'Administrators must retain their administration role');req.user.expertise=text(req.body.expertise,'Expertise',2000,5);req.user.bio=text(req.body.bio,'Bio',5000,10);req.user.role='mentor';c.audit(req.user,'mentor.registered',req.user.id);return publicUser(req.user);});
 const view=m=>({...m,mentorName:s().users.find(u=>u.id===m.mentorId)?.name,requesterName:s().users.find(u=>u.id===m.requesterId)?.name});
 route('get','/mentorships',true,req=>s().mentorships.filter(m=>m.mentorId===req.user.id||m.requesterId===req.user.id).map(view).reverse());
 route('post','/mentorships',true,req=>{const mentor=s().users.find(u=>u.id===req.body.mentorId&&u.role==='mentor'&&u.active&&u.verified);if(!mentor)fail(400,'Choose an active mentor');if(mentor.id===req.user.id)fail(400,'Cannot request yourself');if(req.body.projectId)c.project(req.body.projectId,req.user);if(s().mentorships.some(m=>m.mentorId===mentor.id&&m.requesterId===req.user.id&&m.projectId===(req.body.projectId||null)&&['pending','accepted'].includes(m.status)))fail(409,'An active mentorship request already exists');const m={id:id(),mentorId:mentor.id,requesterId:req.user.id,projectId:req.body.projectId||null,message:text(req.body.message,'Message',4000,5),status:'pending',meetingAt:null,feedback:'',createdAt:stamp()};s().mentorships.push(m);c.notify(mentor.id,'Mentorship request',`${req.user.name}: ${m.message}`,'/mentors');return view(m);});
 route('patch','/mentorships/:id',true,req=>{const m=s().mentorships.find(m=>m.id===req.params.id);if(!m)fail(404,'Mentorship not found');if(m.mentorId!==req.user.id||req.user.role!=='mentor')fail(403,'Only the assigned mentor can respond');m.status=oneOf(req.body.status,['accepted','declined'],'mentorship status');if(req.body.meetingAt!==undefined){const d=Date.parse(req.body.meetingAt);if(!Number.isFinite(d)||d<c.now())fail(400,'Meeting must have a valid future date');m.meetingAt=new Date(d).toISOString();}if(req.body.feedback!==undefined)m.feedback=text(req.body.feedback,'Feedback',5000,0);c.notify(m.requesterId,`Mentorship ${m.status}`,`${req.user.name} responded to your request`,'/mentors');return view(m);});
}
