import {id,text,oneOf,fail,email,publicUser} from './core.js';
const mimes=['application/pdf','text/plain','image/png','image/jpeg','text/csv'];
export function installProjects(c){const {route,store,stamp}=c;const s=()=>store.state;
 c.project=(key,user,leader=false)=>{const p=s().projects.find(p=>p.id===key);if(!p)fail(404,'Project not found');if(!p.memberIds.includes(user.id))fail(403,'Project membership required');if(leader&&p.leaderId!==user.id)fail(403,'Project leader access required');return p;};
 c.projectView=p=>{const {memberIds,tasks,messages,documents,activities,...v}=p;return {...v,problemTitle:c.problem(p.problemId).title,progress:tasks.length?Math.round(100*tasks.filter(t=>t.status==='done').length/tasks.length):0};};
 c.activity=(p,u,action)=>{p.activities.push({id:id(),userName:u.name,action,createdAt:stamp()});for(const uid of p.memberIds)if(uid!==u.id)c.notify(uid,p.name,action,'/projects');};
 const make=(b,u)=>({id:id(),name:text(b.name,'Project name',160,2),description:text(b.description,'Description',10000,5),teamName:text(b.teamName??'','Team name',100,0),problemId:b.problemId,leaderId:u.id,memberIds:[u.id],status:'active',milestones:[],tasks:[],messages:[],documents:[],activities:[],createdAt:stamp()});
 if(c.demoMode&&!s().seededProjects){const lead=s().users.find(u=>u.role==='researcher');const p=make({name:'Harvest resilience pilot',description:'Fictional pilot exploring solar cold storage with farming cooperatives.',teamName:'Green Futures Lab',problemId:s().problems.find(p=>p.status==='verified').id},lead);p.memberIds.push(s().users.find(u=>u.role==='student').id,s().users.find(u=>u.role==='mentor').id);p.milestones=[{title:'Community discovery',completed:true},{title:'Prototype field trial',completed:false}];p.tasks.push({id:id(),title:'Map fictional stakeholder needs',assigneeId:lead.id,dueDate:'2027-01-15',status:'doing'});c.activity(p,lead,'Fictional demonstration project created');s().projects.push(p);s().seededProjects=true;}
 route('get','/projects',true,req=>s().projects.filter(p=>p.memberIds.includes(req.user.id)).map(c.projectView));
 route('post','/projects',true,req=>{const problem=c.problem(req.body.problemId);if(problem.status!=='verified')fail(409,'Projects require an administrator-verified problem');const p=make(req.body,req.user);s().projects.push(p);c.activity(p,req.user,'Project created');c.audit(req.user,'project.created',p.id);return c.projectView(p);});
 route('get','/projects/:id',true,req=>{const p=c.project(req.params.id,req.user);return {...c.projectView(p),members:p.memberIds.map(uid=>publicUser(s().users.find(u=>u.id===uid))),tasks:p.tasks.map(t=>({...t,assigneeName:s().users.find(u=>u.id===t.assigneeId)?.name??'Unassigned'})),messages:p.messages,documents:p.documents.map(({content,...d})=>d),activities:p.activities.slice().reverse(),invitations:p.leaderId===req.user.id?s().invitations.filter(i=>i.projectId===p.id):[]};});
 route('patch','/projects/:id',true,req=>{const p=c.project(req.params.id,req.user,true);if(req.body.status!==undefined)p.status=oneOf(req.body.status,['active','planning','on_hold','completed','archived'],'project status');if(req.body.milestones!==undefined){if(!Array.isArray(req.body.milestones)||req.body.milestones.length>50)fail(400,'Milestones must be an array of at most 50 items');p.milestones=req.body.milestones.map(m=>typeof m==='string'?{title:text(m,'Milestone',300),completed:false}:{title:text(m.title,'Milestone',300),completed:m.completed===true});}c.activity(p,req.user,'Project progress updated');return c.projectView(p);});
 route('post','/projects/:id/invitations',true,async req=>{const p=c.project(req.params.id,req.user,true);const to=email(req.body.email);const u=s().users.find(u=>u.email===to&&u.active&&u.verified);if(!u)fail(400,'Invite a registered, verified member');if(p.memberIds.includes(u.id)||s().invitations.some(i=>i.projectId===p.id&&i.email===to&&i.status==='pending'))fail(409,'Already a member or invited');const invitation={id:id(),projectId:p.id,projectName:p.name,email:to,userId:u.id,inviterName:req.user.name,status:'pending',createdAt:stamp()};s().invitations.push(invitation);c.notify(u.id,'Project invitation',`${req.user.name} invited you to ${p.name}`,'/projects');if(c.demoMode&&to.endsWith('@afrisolve.demo'))await c.sendMail(to,'Project invitation',`You have been invited to the fictional project ${p.name}. Sign in and open Invitations to accept or decline.`);c.activity(p,req.user,`Invited ${u.name}`);return invitation;});
 route('get','/invitations',true,req=>s().invitations.filter(i=>i.userId===req.user.id));
 route('post','/invitations/:id/respond',true,req=>{const i=s().invitations.find(i=>i.id===req.params.id);if(!i)fail(404,'Invitation not found');if(i.userId!==req.user.id)fail(403,'This invitation belongs to another member');if(i.status!=='pending')fail(409,'Invitation already answered');if(typeof req.body.accept!=='boolean')fail(400,'accept must be boolean');const p=s().projects.find(p=>p.id===i.projectId);i.status=req.body.accept?'accepted':'declined';if(req.body.accept&&!p.memberIds.includes(req.user.id))p.memberIds.push(req.user.id);c.activity(p,req.user,`Invitation ${i.status}`);return {ok:true};});
 route('post','/projects/:id/tasks',true,req=>{const p=c.project(req.params.id,req.user,true);const assigneeId=req.body.assigneeId||req.user.id;if(!p.memberIds.includes(assigneeId))fail(400,'Assignee must be a project member');const dueDate=req.body.dueDate??'';if(dueDate&&(!/^\d{4}-\d{2}-\d{2}$/.test(dueDate)||!Number.isFinite(Date.parse(dueDate))))fail(400,'Invalid due date');const task={id:id(),title:text(req.body.title,'Task title',300),assigneeId,dueDate,status:'todo'};p.tasks.push(task);c.activity(p,req.user,`Task created: ${task.title}`);return {...task,assigneeName:s().users.find(u=>u.id===assigneeId).name};});
 route('patch','/projects/:id/tasks/:taskId',true,req=>{const p=c.project(req.params.id,req.user);const task=p.tasks.find(t=>t.id===req.params.taskId);if(!task)fail(404,'Task not found');if(req.user.id!==p.leaderId&&req.user.id!==task.assigneeId)fail(403,'Only assignee or leader can update a task');task.status=oneOf(req.body.status,['todo','doing','done'],'task status');c.activity(p,req.user,`Task ${task.status}: ${task.title}`);return {...task,assigneeName:s().users.find(u=>u.id===task.assigneeId)?.name};});
 route('post','/projects/:id/messages',true,req=>{const p=c.project(req.params.id,req.user);const m={id:id(),userId:req.user.id,userName:req.user.name,text:text(req.body.text,'Message',5000),createdAt:stamp()};p.messages.push(m);c.activity(p,req.user,'Posted a team message');return m;});
 route('post','/projects/:id/documents',true,req=>{const p=c.project(req.params.id,req.user);const mime=oneOf(req.body.mime,mimes,'document type');const name=text(req.body.name,'Filename',150).replace(/[\\/\r\n\x00-\x1f]/g,'_');const content=text(req.body.content,'Base64 content',2800000);if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(content))fail(400,'Invalid base64 content');const bytes=Buffer.from(content,'base64');if(!bytes.length||bytes.length>2097152)fail(400,'Document limit is 2 MB');if(mime==='application/pdf'&&!bytes.subarray(0,5).equals(Buffer.from('%PDF-')))fail(400,'Invalid PDF signature');if(mime==='image/png'&&bytes.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')fail(400,'Invalid PNG signature');if(mime==='image/jpeg'&&bytes.subarray(0,3).toString('hex')!=='ffd8ff')fail(400,'Invalid JPEG signature');const d={id:id(),name,mime,content,size:bytes.length,userId:req.user.id,createdAt:stamp()};p.documents.push(d);c.activity(p,req.user,`Document shared: ${name}`);const {content:_,...view}=d;return view;});
 route('get','/projects/:id/documents/:documentId',true,(req,res)=>{const p=c.project(req.params.id,req.user);const d=p.documents.find(x=>x.id===req.params.documentId);if(!d)fail(404,'Document not found');res.type(d.mime).attachment(d.name).send(Buffer.from(d.content,'base64'));});
 route('patch','/notifications/:id',true,req=>{const n=s().notifications.find(n=>n.id===req.params.id&&n.userId===req.user.id);if(!n)fail(404,'Notification not found');if(req.body.read!==true)fail(400,'read must be true');n.read=true;return n;});
}
