import {id,text,oneOf,fail,sectors} from './core.js';
export function installRepository(c){const {route,store,stamp}=c;const s=()=>store.state;
 c.problem=(key)=>{const p=s().problems.find(p=>p.id===key);if(!p)fail(404,'Problem not found');return p;};
 c.problemView=(p,u)=>({...p,authorName:s().users.find(x=>x.id===p.authorId)?.name??'Former member',score:s().votes.filter(v=>v.problemId===p.id).length,voted:s().votes.some(v=>v.problemId===p.id&&v.userId===u?.id),commentsCount:s().comments.filter(x=>x.problemId===p.id).length});
 const fields=(b,partial=false)=>{const out={};for(const k of ['title','description','evidence','sector','country','region','sdg','priority']){if(partial&&b[k]===undefined)continue;const v=b[k];if(k==='sdg'){const n=Number(v);if(!Number.isInteger(n)||n<1||n>17)fail(400,'SDG must be 1–17');out[k]=n;}else if(k==='priority')out[k]=oneOf(v,['low','medium','high','critical'],'priority');else if(k==='sector')out[k]=oneOf(v,sectors,'sector');else out[k]=text(v??(k==='region'?'':undefined),k,k==='title'?180:10000,k==='region'?0:k==='description'?20:2);}return out;};
 if(c.demoMode&&!s().seededProblems){const author=s().users.find(u=>u.role==='researcher');const records=[['Solar-powered cold storage for smallholder farmers','Agriculture','Nigeria',2,'verified'],['Reliable water testing in rural schools','Water & Sanitation','Kenya',6,'verified'],['Offline learning resources for remote classrooms','Education','Ghana',4,'pending'],['Community clean cooking access','Energy','Rwanda',7,'pending']];for(const [title,sector,country,sdg,status] of records){const p={id:id(),title,description:`Fictional demonstration: ${title.toLowerCase()}. Communities seek affordable, locally maintained approaches and a participatory pilot.`,evidence:'Fictional sample interviews; not real research evidence.',sector,country,region:'Demonstration region',sdg,priority:'high',status,authorId:author.id,createdAt:stamp()};s().problems.push(p);if(status==='verified'){for(const u of s().users.filter(u=>['student','innovator'].includes(u.role)))s().votes.push({problemId:p.id,userId:u.id});c.audit(s().users.find(u=>u.role==='admin'),'problem.seed-approved',p.id);}}s().seededProblems=true;}
 route('get','/problems',true,req=>{let list=s().problems;for(const k of ['sector','country','status','sdg','priority','region'])if(req.query[k])list=list.filter(p=>String(p[k]).toLowerCase()===String(req.query[k]).toLowerCase());if(req.query.q){const q=text(req.query.q,'Search',200).toLowerCase();list=list.filter(p=>(p.title+' '+p.description+' '+p.evidence).toLowerCase().includes(q));}if(req.query.since){const time=Date.parse(req.query.since);if(!Number.isFinite(time))fail(400,'Invalid since date');list=list.filter(p=>Date.parse(p.createdAt)>=time);}const result=list.map(p=>c.problemView(p,req.user));return result.sort(req.query.sort==='score'||req.query.sort==='popular'?(a,b)=>b.score-a.score:req.query.sort==='oldest'?(a,b)=>a.createdAt.localeCompare(b.createdAt):(a,b)=>b.createdAt.localeCompare(a.createdAt));});
 route('post','/problems',true,req=>{const p={id:id(),...fields(req.body),status:'pending',authorId:req.user.id,createdAt:stamp()};s().problems.push(p);c.audit(req.user,'problem.submitted',p.id);for(const u of s().users.filter(u=>u.role==='admin'&&u.active))c.notify(u.id,'Problem awaiting review',p.title,'/problems');return c.problemView(p,req.user);});
 route('get','/problems/:id',true,req=>{const p=c.problem(req.params.id);return {...c.problemView(p,req.user),comments:s().comments.filter(x=>x.problemId===p.id).map(x=>({...x,userName:s().users.find(u=>u.id===x.userId)?.name})),similar:s().problems.filter(x=>x.id!==p.id&&(x.sector===p.sector||x.sdg===p.sdg)).slice(0,5).map(x=>c.problemView(x,req.user))};});
 route('patch','/problems/:id',true,req=>{const p=c.problem(req.params.id);if(p.authorId!==req.user.id||p.status!=='pending')fail(403,'Only the author can edit a pending problem');Object.assign(p,fields(req.body,true));s().votes=s().votes.filter(v=>v.problemId!==p.id);c.audit(req.user,'problem.updated-votes-reset',p.id);return c.problemView(p,req.user);});
 route('post','/problems/:id/vote',true,req=>{const p=c.problem(req.params.id);if(p.authorId===req.user.id)fail(403,'Authors cannot verify their own problem');if(['rejected','archived'].includes(p.status))fail(409,'Problem is closed');const v=s().votes.find(x=>x.problemId===p.id&&x.userId===req.user.id);if(v)s().votes=s().votes.filter(x=>x!==v);else s().votes.push({problemId:p.id,userId:req.user.id});const {score,voted}=c.problemView(p,req.user);return {score,voted};});
 route('post','/problems/:id/comments',true,req=>{const p=c.problem(req.params.id);const comment={id:id(),problemId:p.id,userId:req.user.id,userName:req.user.name,text:text(req.body.text,'Comment',4000),createdAt:stamp()};s().comments.push(comment);if(p.authorId!==req.user.id)c.notify(p.authorId,'New problem discussion',p.title,'/problems');return comment;});
 route('post','/problems/:id/flag',true,req=>{const p=c.problem(req.params.id);if(s().flags.some(f=>f.problemId===p.id&&f.userId===req.user.id&&!f.resolved))fail(409,'Already flagged');s().flags.push({id:id(),problemId:p.id,problemTitle:p.title,userId:req.user.id,reason:text(req.body.reason,'Reason',2000,5),resolved:false,createdAt:stamp()});return {ok:true};});
 route('patch','/admin/problems/:id','admin',req=>{const p=c.problem(req.params.id);const status=oneOf(req.body.status,['verified','rejected','archived'],'status');if(status==='verified'&&new Set(s().votes.filter(v=>v.problemId===p.id&&v.userId!==p.authorId).map(v=>v.userId)).size<2)fail(409,'At least two independent non-author community votes are required');p.status=status;if(req.body.reason!==undefined)p.moderationReason=text(req.body.reason,'Reason',2000,0);c.audit(req.user,`problem.${status}`,p.id);c.notify(p.authorId,'Problem moderation update',`${p.title}: ${status}`,'/problems');return c.problemView(p,req.user);});
}
