import React,{useState} from 'react';
import {Bell, CheckCheck} from 'lucide-react';
import {api,useData,list,date,Badge,Empty,Panel,PageTitle,Field,ActionForm,ActionButton,Resource,Avatar,Notice} from './shared.jsx';
import {Invitations} from './Projects.jsx';

export function Notifications(){
 const resource=useData('/notifications',[]);
 return <><PageTitle eyebrow="Keep the conversation moving" title="Notifications" description="Team invitations, community updates, and guidance in one place."/><Panel title="Your updates"><Resource resource={resource}>{list(resource.data).length?resource.data.map(n=><article className={'notification '+(n.read?'read':'unread')} key={n.id}><span className="notification-icon">{n.read?<CheckCheck size={20}/>:<Bell size={20}/>}</span><div><div className="section-heading"><h3>{n.title}</h3><Badge>{n.read?'Read':'Unread'}</Badge></div><p>{n.body}</p><small>{date(n.createdAt)}</small><div className="actions">{/^\/(?!\/)/.test(n.link||'')&&<a className="text-link" href={'#'+n.link}>Open update →</a>}{!n.read&&<ActionButton onClick={async()=>{await api('/notifications/'+n.id,'PATCH',{read:true});resource.reload();}}>Mark as read</ActionButton>}</div></div></article>):<Empty title="You're all caught up">Your next community or project update will appear here.</Empty>}</Resource></Panel><Invitations/></>;
}

export function Profile({user,setUser,config}){
 const [avatar,setAvatar]=useState(user.avatar||''),[photoError,setPhotoError]=useState(''),[reading,setReading]=useState(false);
 async function choosePhoto(e){const file=e.target.files[0];setPhotoError('');if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)){setPhotoError('Choose a PNG or JPEG photo.');e.target.value='';return;}if(file.size>262144){setPhotoError('Your profile photo must be 256 KB or smaller.');e.target.value='';return;}setReading(true);try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Photo could not be read.'));reader.readAsDataURL(file);});setAvatar(data);}catch(error){setPhotoError(error.message);}finally{setReading(false);}}
 return <><PageTitle eyebrow="The person behind the possibilities" title="My profile" description="Help collaborators understand your interests, experience, and local perspective."/><div className="profile-grid"><Panel className="profile-summary"><Avatar user={user} size="large"/><h2>{user.name}</h2><p>{user.email}</p><div className="tags"><Badge>{user.role}</Badge><Badge>{user.verified?'Verified email':'Unverified email'}</Badge></div><p>{user.country}{user.institution?' · '+user.institution:''}</p><p className="muted">Roles are managed by administrators. Your email is linked to your verified account.</p></Panel><Panel title="Your details"><ActionForm submit="Save profile" success="Profile saved." onSubmit={async data=>{if(reading)throw new Error('Please wait for the photo to finish loading.');setUser(await api('/profile','PATCH',{...data,avatar}));}}><div className="photo-editor"><Avatar user={{...user,avatar}} size="large" preview/><div><Field label="Profile photo" type="file" accept="image/png,image/jpeg" onChange={choosePhoto}/><small>PNG or JPEG · up to 256 KB. Choose a photo you have permission to use.</small>{avatar&&<button className="text-button" type="button" onClick={()=>setAvatar('')}>Remove photo</button>}</div></div><Notice error={photoError}/><Field label="Full name" name="name" defaultValue={user.name} required minLength={2} maxLength={100}/><div className="form-grid"><Field label="Country" name="country" options={list(config.countries)} defaultValue={user.country} required/><Field label="Institution or organisation" name="institution" defaultValue={user.institution||''} maxLength={200}/></div><Field label="About you" name="bio" type="textarea" defaultValue={user.bio||''} maxLength={2000}/><Field label="Areas of expertise" name="expertise" defaultValue={user.expertise||''} maxLength={2000}/></ActionForm></Panel></div></>;
}
