import React,{useState} from 'react';
import {Download,BarChart3} from 'lucide-react';
import {useData,list,date,Empty,Panel,PageTitle,Field,Resource} from './shared.jsx';
import {Metrics} from './Dashboard.jsx';
function Distribution({title,items}){const max=Math.max(1,...list(items).map(v=>Number(v.count)||0));return <Panel title={title}>{list(items).length?<div className="distribution">{items.map(v=><div className="distribution-row" key={v.name}><div><span>{v.name}</span><strong>{v.count}</strong></div><progress max={max} value={Number(v.count)||0} aria-label={v.name+' problem count'}/></div>)}</div>:<Empty title="No data yet">This distribution will reflect repository submissions.</Empty>}</Panel>;}
export default function Analytics({config}){
 const resource=useData('/analytics'),projects=useData('/projects',[]);const [projectId,setProjectId]=useState('');const d=resource.data;
 return <><PageTitle eyebrow="Measure activity. Question assumptions." title="Analytics & reports" description="A transparent view of participation, community challenges, and project progress."/><div className="notice"><BarChart3 size={20}/><span>{config.demoMode?'Fictional sample data. These counts describe this academic demonstration, not real community outcomes.':'These metrics measure platform activity, not independently verified real-world impact.'}</span></div><Resource resource={resource}>{d&&<><Metrics data={d} extended/><div className="two-column"><Distribution title="Problems by sector" items={d.sectors}/><Distribution title="Problems by country" items={d.countries}/></div><div className="two-column"><Panel title="Project task completion"><div className="completion-number"><strong>{d.completedTasks??0}</strong><span>of {d.totalTasks??0} tasks complete</span></div><progress max={d.totalTasks||1} value={d.completedTasks||0} aria-label="Completed project tasks"/><p className="muted">Task totals cover your accessible projects. Completion does not demonstrate community impact.</p></Panel><Panel title="Export a report"><p>Download a platform summary or a report for a project you belong to.</p><Resource resource={projects}><Field label="Report scope" value={projectId} onChange={e=>setProjectId(e.target.value)} options={[{value:'',label:'Platform aggregate'},...list(projects.data).map(p=>({value:p.id,label:p.name}))]}/><div className="actions report-downloads">{['csv','pdf'].map(format=><a className={'button '+(format==='csv'?'secondary':'')} key={format} href={'/api/reports?format='+format+(projectId?'&projectId='+encodeURIComponent(projectId):'')}><Download size={17}/>Download {format.toUpperCase()}</a>)}</div></Resource></Panel></div><Panel title="Recent project activity">{list(d.recentActivity).length?d.recentActivity.map((a,i)=><div className="activity" key={a.id||i}><span className="activity-dot"/><div><strong>{a.action||a.title||a.text}</strong><small>{a.userName||a.projectName||'Workspace'} · {date(a.createdAt)}</small></div></div>):<Empty title="No recent activity">Activity from your accessible projects will appear here.</Empty>}</Panel></>}</Resource></>;
}
