import React,{useState,useEffect} from 'react';
import Auth from './Auth.jsx';
import Problems from './Problems.jsx';
import Research from './Research.jsx';
import Projects from './Projects.jsx';
import Mentors from './Mentors.jsx';
import Admin from './Admin.jsx';
import {Notifications,Profile} from './Account.jsx';
import {Overview} from './Dashboard.jsx';
import Analytics from './Analytics.jsx';
import { Sprout, LayoutDashboard, Compass, Sparkles, FolderKanban, UsersRound, Bell, ChartNoAxesCombined, ShieldCheck, UserRound, LogOut, Menu, X, Mail, ArrowUpRight } from 'lucide-react';
import { api,useData,list,Notice,Loading,PageTitle,Panel,ActionButton,Avatar } from './shared.jsx';
const navigation=[['overview','Overview',LayoutDashboard],['problems','Problem repository',Compass],['research','AI research',Sparkles],['projects','Project workspace',FolderKanban],['mentors','Mentor network',UsersRound],['notifications','Notifications',Bell],['analytics','Analytics & reports',ChartNoAxesCombined],['profile','My profile',UserRound],['admin','Administration',ShieldCheck]];
export function Brand(){return <a className="brand" href="#/overview"><span className="brand-symbol"><Sprout size={25}/></span><span>AfriSolve<span className="brand-ai">AI</span><small>LOCAL INSIGHT. SHARED PROGRESS.</small></span></a>;}
function Demo({onLogin}){const personas=useData('/demo/personas',[]);return <section className="demo-section"><div className="section-heading"><h2>Explore a demo workspace</h2><span className="badge">Fictional personas</span></div><p>Fictional data for academic demonstration. No real community outcomes are claimed.</p><Notice error={personas.error}/><div className="persona-grid">{list(personas.data).map(p=><ActionButton key={p.id} onClick={async()=>{const r=await api('/demo/login','POST',{id:p.id});onLogin(r.user);}}><span className="avatar">{p.name?.slice(0,1)}</span><span>Enter as {p.name}<small>{p.role} · {p.country}</small></span><ArrowUpRight size={16}/></ActionButton>)}</div></section>;}
function Landing({config,onLogin,route}){return <div className="landing"><header><Brand/><span className="eyebrow">An African-centered innovation platform</span></header><div className="landing-grid"><section className="mission"><span className="eyebrow">FROM CHALLENGE TO CHANGE</span><h1>Local challenges.<br/><em>Collective possibility.</em></h1><p>A shared space to surface Africa’s everyday challenges, build on evidence, and bring the right people together to solve them.</p><div className="mission-steps"><span>01 <strong>Discover problems</strong></span><span>02 <strong>Develop understanding</strong></span><span>03 <strong>Deliver together</strong></span></div><div className="mission-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><Sprout size={95}/><span>Rooted in community.<br/>Built for possibility.</span></div></section><section className="entry"><Auth config={config} onLogin={onLogin} route={route}/>{config.demoMode&&<Demo onLogin={onLogin}/>}</section></div><footer>AfriSolve AI · Academic prototype by Chibuzor Moses Uzowuru <span>Research responsibly. Collaborate openly.</span></footer></div>;}
export default function App(){const boot=useData('/config'),session=useData('/auth/me');const [user,setUser]=useState(null),[route,setRoute]=useState(window.location.hash.slice(1)||'/overview'),[open,setOpen]=useState(false);
 useEffect(()=>{if(session.data)setUser(session.data.user);},[session.data]);
 useEffect(()=>{const change=()=>{setRoute(window.location.hash.slice(1)||'/overview');setOpen(false);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 const onLogin=u=>{setUser(u);window.location.hash='/overview';};
 if(boot.loading||session.loading)return <Loading/>;if(boot.error||session.error)return <div className="boot-error"><Brand/><Notice error={boot.error||session.error}/><button onClick={()=>{boot.reload();session.reload();}}>Retry connection</button></div>;
 if(!user)return <Landing config={boot.data} onLogin={onLogin} route={route}/>;
 const current=route.split('?')[0].split('/')[1]||'overview';
 return <div className="app"><a href="#main-content" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus();}}>Skip to content</a>{open&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={'sidebar '+(open?'open':'')}><Brand/><button className="mobile-close icon-button" aria-label="Close navigation" onClick={()=>setOpen(false)}><X/></button><span className="nav-caption">WORKSPACE</span><nav aria-label="Workspace">{navigation.filter(([key])=>key!=='admin'||user.role==='admin').map(([key,label,Icon])=><a key={key} href={'#/'+key} aria-current={current===key?'page':undefined}><Icon size={19}/>{label}{key==='research'&&<span className="nav-new">AI</span>}</a>)}</nav><div className="sidebar-bottom"><div className="impact-note"><Sprout size={20}/><strong>Small insights.<br/>Lasting change.</strong><p>Better solutions begin with the people closest to the problem.</p></div><a href="#/profile" className="user-card"><Avatar user={user}/><span><strong>{user.name}</strong><small>{user.role}</small></span></a><ActionButton className="logout" onClick={async()=>{await api('/auth/logout','POST',{});setUser(null);}}><LogOut size={16}/> Sign out</ActionButton></div></aside><div className="main-shell"><header className="topbar"><button className="mobile-menu icon-button" aria-label="Open navigation" aria-expanded={open} onClick={()=>setOpen(!open)}><Menu/></button><div className="breadcrumb">Workspace <span>/</span> <strong>{navigation.find(n=>n[0]===current)?.[1]||'Explore'}</strong></div><div className="topbar-actions">{boot.data.demoMode&&<span className="demo-indicator"><i/>Fictional demo</span>}<a href="#/notifications" className="icon-button" aria-label="View notifications"><Bell size={20}/></a><a href="#/profile" aria-label="My profile"><Avatar user={user} size="small"/></a></div></header><main id="main-content" tabIndex="-1">{current==='admin'?<Admin user={user} config={boot.data} onRestored={()=>{setUser(null);window.location.hash='/login';}}/>:current==='mentors'?<Mentors user={user} setUser={setUser}/>:current==='projects'?<Projects route={route} user={user}/>:current==='research'?<Research route={route} config={boot.data}/>:current==='problems'?<Problems route={route} config={boot.data} user={user}/>:current==='analytics'?<Analytics config={boot.data}/>:current==='notifications'?<Notifications/>:current==='profile'?<Profile user={user} setUser={setUser} config={boot.data}/>:<Overview user={user} config={boot.data}/>}</main><footer className="workspace-footer"><span>AfriSolve AI · An academic prototype</span><span>People first. Evidence led. Africa centered.</span></footer></div></div>;
}
