import React,{useEffect,useState} from 'react';
import {api,Field,Panel,Notice,useAction,list,date,Empty} from './shared.jsx';
export function MailPreview(){const [messages,setMessages]=useState(null);const action=useAction();return <details className="mail-preview"><summary>Demo mailbox · local preview only</summary><p>Only fictional @afrisolve.demo addresses are available. Messages shown here are not proof of email delivery.</p><form onSubmit={e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');action.run(async()=>setMessages(await api('/demo/mail?email='+encodeURIComponent(email))),'');}}><Field label="Demo email address" name="email" type="email" required placeholder="name@afrisolve.demo"/><button className="secondary" disabled={action.busy}>Open demo mailbox</button></form><Notice {...action}/>{messages&&list(messages).map(m=><article className="mail" key={m.id}><strong>{m.subject}</strong><small>{date(m.createdAt)} · {m.to}</small><p className="pre-wrap">{m.text}</p>{(m.text?.match(/https?:\/\/[^\s<>]+/g)||[]).map((url,i)=>{try {const parsed=new URL(url);if(parsed.origin!==window.location.origin)return null;return <a key={i} href={parsed.pathname+parsed.search+parsed.hash}>Open account action</a>;}catch{return null;}})}</article>)}{messages?.length===0&&<Empty title="No preview messages">Check the recipient address or request a new message.</Empty>}</details>;}
export default function Auth({config,onLogin,route}){const [mode,setMode]=useState('login');const [serverMessage,setServerMessage]=useState('');const action=useAction();const params=new URLSearchParams(route.split('?')[1]||window.location.search);const token=params.get('token')||'';
 useEffect(()=>{const part=route.split('?')[0].split('/')[1];if(['login','register','verify','forgot','reset'].includes(part))setMode(part);else {const action=new URLSearchParams(window.location.search).get('action');if(['verify','reset'].includes(action))setMode(action);}},[route]);
 const change=next=>{setMode(next);setServerMessage('');action.error='';};
 const titles={login:'Welcome back',register:'Create your account',verify:'Verify your email',forgot:'Recover your account',reset:'Set a new password'};
 async function submit(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));await action.run(async()=>{let r;if(mode==='login'){r=await api('/auth/login','POST',{...data,remember:data.remember==='on'});onLogin(r.user);}else{r=await api('/auth/'+mode,'POST',data);setServerMessage(r.message||'Request completed.');}},'');}
 return <Panel title={titles[mode]}><p>{mode==='login'?'Pick up where your community left off.':'Build a foundation for responsible collaboration.'}</p>{['login','register'].includes(mode)&&<div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>change('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>change('register')}>Create account</button></div>}<form className="form" onSubmit={submit} key={mode}><fieldset disabled={action.busy}>{mode==='register'&&<Field label="Full name" name="name" autoComplete="name" required/>}{['login','register','forgot'].includes(mode)&&<Field label="Email address" name="email" type="email" autoComplete="email" required/>}{['verify','reset'].includes(mode)&&<Field label="Verification or recovery token" name="token" defaultValue={token} required/>}{['login','register','reset'].includes(mode)&&<Field label={mode==='reset'?'New password':'Password'} name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?undefined:10} required/>}{mode==='register'&&<><div className="form-grid"><Field label="Country" name="country" options={list(config.countries)} required/><Field label="Role" name="role" options={list(config.roles).filter(r=>r!=='admin')} required/></div><Field label="Institution or organisation" name="institution"/><p className="muted">Use at least 10 characters with letters and numbers. Email verification is required before signing in.</p></>}{mode==='login'&&<Field label="Remember this browser" name="remember" type="checkbox"/>}<Notice error={action.error} message={serverMessage}/><button className="full" type="submit">{action.busy?'Working…':({login:'Sign in to workspace',register:'Register account',verify:'Verify email',forgot:'Send recovery link',reset:'Reset password'}[mode])}</button></fieldset></form><div className="auth-links">{mode==='login'?<><button className="text-button" onClick={()=>change('forgot')}>Forgot password?</button><button className="text-button" onClick={()=>change('verify')}>Verify email</button></>:<button className="text-button" onClick={()=>change('login')}>Back to sign in</button>}{mode==='forgot'&&<button className="text-button" onClick={()=>change('reset')}>I have a reset token</button>}</div>{config.demoMode&&<MailPreview/>}</Panel>;
}
