import React from 'react';
import {Compass,UsersRound,FolderKanban,CheckCircle2,ArrowUpRight,Plus,Sprout,Sparkles} from 'lucide-react';
import {useData,list,Badge,Empty,Panel,PageTitle,LinkButton,Resource} from './shared.jsx';
import {ProblemCard} from './Problems.jsx';

export function Metrics({data,extended=false}){
 const items=[['problems','Community problems',Compass,'Challenges made visible'],['verified','Verified problems',CheckCircle2,'Community + admin review'],['projects','Collaborative projects',FolderKanban,'Working toward solutions'],['users','Community members',UsersRound,'Different perspectives, shared purpose']];
 if(extended)items.push(['researchSessions','Research briefs',Sparkles,'Questions explored'],['mentorships','Mentorship requests',UsersRound,'Experience shared']);
 return <div className="metrics">{items.map(([key,label,Icon,caption])=><article className="metric" key={key}><div className="metric-top"><span>{label}</span><Icon size={19}/></div><strong>{data[key]??0}</strong><small>{caption}</small></article>)}</div>;
}
export function Overview({user,config}){
 const analytics=useData('/analytics'),problems=useData('/problems',[]),projects=useData('/projects',[]);
 return <><PageTitle eyebrow="Overview · your community at a glance" title="Overview" description="Your next step toward meaningful change starts here."><LinkButton to="/problems/new"><Plus size={17}/> Submit a problem</LinkButton></PageTitle><section className="welcome-banner"><div><span className="eyebrow">ROOTED IN COMMUNITY. BUILT TOGETHER.</span><h2>Welcome back, {user.name?.split(' ')[0]||'collaborator'}.</h2><p>Big change begins with a local insight.<br/>What will you help move forward today?</p><LinkButton secondary to="/problems">Explore community challenges</LinkButton></div><div className="welcome-art" aria-hidden="true"><div className="art-ring"/><Sprout size={92}/><span>Local insight.<br/>Shared progress.</span></div></section>{config.demoMode&&<p className="data-note"><span className="status-dot"/> Fictional demonstration data · Counts reflect this workspace, not real-world impact.</p>}<Resource resource={analytics}>{analytics.data&&<Metrics data={analytics.data}/>}</Resource><div className="dashboard-grid"><div><div className="section-heading"><div><span className="eyebrow">LISTEN TO WHAT MATTERS</span><h2>Community challenges</h2></div><a className="text-link" href="#/problems">View all <ArrowUpRight size={15}/></a></div><Resource resource={problems}>{list(problems.data).length?<div className="card-grid dashboard-cards">{problems.data.slice(0,4).map(p=><ProblemCard key={p.id} problem={p}/>)}</div>:<Empty title="Be the first to surface a challenge">Share a local problem with evidence and community context.</Empty>}</Resource></div><div><Panel title="Your active work" action={<a href="#/projects" aria-label="View all projects"><ArrowUpRight size={18}/></a>}><Resource resource={projects}>{list(projects.data).length?projects.data.slice(0,4).map(p=><a className="project-mini" href={'#/projects/'+p.id} key={p.id}><div className="section-heading"><FolderKanban size={19}/><Badge>{p.status}</Badge></div><h3>{p.name}</h3><div className="progress-label"><span>Task completion</span><strong>{p.progress||0}%</strong></div><progress max="100" value={p.progress||0} aria-label={p.name+' completion'}/></a>):<Empty title="Make room for collaboration">Create a project from a verified problem or accept an invitation.</Empty>}</Resource></Panel><Panel className="research-prompt"><Sparkles size={25}/><h2>A new perspective starts with a question.</h2><p>Explore possible approaches and source-discovery pathways. Always check the evidence.</p><a className="list-link" href="#/research">Open research studio <ArrowUpRight size={18}/></a></Panel><a className="mentor-prompt" href="#/mentors"><UsersRound size={25}/><div><strong>You don’t have to solve it alone.</strong><small>Find a mentor who understands your field.</small></div><ArrowUpRight size={18}/></a></div></div></>;
}
